AWSTemplateFormatVersion: "2010-09-09"
Description: "MariaDB server in private subnet for OJT practice."

Parameters: 
  MariaDBServerPrivateIP:
    Description: IP address allowed to access EC2
    Type: String

  MariaDBSubnetCIDR:
    Description: CIDR block for private subnet
    Type: String

  SubnetID:
    Description: Subnet ID for private subnet
    Type: String

  VPCID:
    Description: VPC ID for Security Group
    Type: String

Resources:
     # MariaDBサーバー(プライベートサブネットに配置)
    MariaDB:
     Type: AWS::EC2::Instance
     Properties:
       ImageId: ami-013a28d7c2ea10269
       InstanceType: t3.micro
       
       NetworkInterfaces: 
        - AssociatePublicIpAddress: "false"
          DeviceIndex: "0"
          PrivateIpAddress: !Ref MariaDBServerPrivateIP
          SubnetId: !Ref SubnetID #stack outputを利用
          GroupSet: 
            - !Ref MariaDBSG
       Tags: 
        - Key: Name
          Value: "MariaDB"
       UserData: String

      # セキュリティグループ(プライベートサブネット用)
    MariaDBSG:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupName: "MariaDBSG"
        GroupDescription: "Allow access from MariaDBServerPrivateIP"
        VpcId: !Ref VPCID #他ファイルのアウトプットを参照
        SecurityGroupIngress:
        # ssh
         - IpProtocol: tcp
           FromPort: 22
           ToPort: 22 
           CidrIp: !Ref MariaDBSubnetCIDR

        # mariadb
         - IpProtocol: tcp
           FromPort: 3306
           ToPort: 3306
           CidrIp: !Ref MariaDBSubnetCIDR

Outputs:
    MariaDBInstanceId:
      Description: "MariaDB Instance ID"
      Value: !Ref MariaDB

    MariaDBSGId:
      Description: "Security Group ID for MariaDB"
      Value: !Ref MariaDBSG  

        