AWSTemplateFormatVersion: "2010-09-09"
Description: "EC2 instance in pubric subnet for OJT pracrice."

Parameters: 

  MyIP:
    Description: IP address allowed to access EC2
    Type: String

  PubWebSubnetCIDR:
    Description: CIDR block for public subnet
    Type: String


Resources:
     # EC2インスタンス(パブリックサブネットに配置)
    EC2InstancePubric:
     Type: AWS::EC2::Instance
     Properties:
       ImageId: ami-013a28d7c2ea10269
       InstanceType: t3.micro
       
       IamInstanceProfile: !Ref IamRoleBox
       NetworkInterfaces: 
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          PrivateIpAddress: !Ref MyIP
          SubnetId: !ImportValue haraPractice2024-PublicWebSubnetId #他ファイルのアウトプットを参照
          GroupSet: 
            - !Ref EC2SPubSG
       Tags: 
        - Key: Name
          Value: "EC2InstancePubric"
       UserData: String

      # セキュリティグループ(パブリックサブネット用)
    EC2SPubSG:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupName: "EC2SPubSG"
        GroupDescription: "Allow access from PubWebSubnetIP"
        VpcId: !ImportValue haraPractice2024-VpcId #他ファイルのアウトプットを参照
        SecurityGroupIngress:
        # http
         - IpProtocol: tcp
           FromPort: 80
           ToPort: 80
           CidrIp: !Ref PubWebSubnetCIDR

    
    IamRoleBox:
      Type: AWS::IAM::InstanceProfile
      Properties:
        Roles:
          - !Ref IamRole


    IamRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Principal:
                Service: "ec2.amazonaws.com"
              Action: "sts:AssumeRole"
        # Policies:
        #   - PolicyName: "root"
        #     PolicyDocument:
        #       Version: "2012-10-17"
        #       Statement:
        #         - Effect: "Allow"
        #           Action: "*"
        #           Resource: "*"
        ManagedPolicyArns:
             - arn:aws:iam::aws:policy/AmazonS3FullAccess
             - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
            



    
        

Outputs:
    EC2PubId:
      Description: "EC2 instance ID"
      Value: !Ref EC2InstancePubric

    EC2PubSGId:
      Description: "Security Group ID for EC2 instance"
      Value: !Ref EC2SPubSG      