AWSTemplateFormatVersion: "2010-09-09"
Description: "EC2 instance in private subnet for OJT pracrice."

Parameters: 
  MyIP:
    Description: IP address allowed to access EC2
    Type: String

  PrivateDBSubnetCIDR:
    Description: CIDR block for private subnet
    Type: String


Resources:
     # EC2インスタンス(プライベートサブネットに配置)
    EC2InstancePrivate:
     Type: AWS::EC2::Instance
     Properties:
       ImageId: ami-013a28d7c2ea10269
       InstanceType: t3.micro
       
       NetworkInterfaces: 
        - AssociatePublicIpAddress: "false"
          DeviceIndex: "0"
          PrivateIpAddress: !Ref MyIP
          SubnetId: !ImportValue haraPractice2024-PrivateDBSubnetId #他ファイルのアウトプットを参照
          GroupSet: 
            - !Ref EC2SPriSG
       Tags: 
        - Key: Name
          Value: "EC2InstancePrivate"
       UserData: String

      # セキュリティグループ(プライベートサブネット用)
    EC2SPriSG:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupName: "EC2SPriSG"
        GroupDescription: "Allow access from MyIP"
        VpcId: !ImportValue haraPractice2024-VpcId #他ファイルのアウトプットを参照
        SecurityGroupIngress:
        # ssh
         - IpProtocol: tcp
           FromPort: 22
           ToPort: 22 
           CidrIp: !Ref PrivateDBSubnetCIDR

        # mariadb
         - IpProtocol: tcp
           FromPort: 3306
           ToPort: 3306
           CidrIp: !Ref PrivateDBSubnetCIDR

Outputs:
    EC2PriId:
      Description: "EC2 instance ID"
      Value: !Ref EC2InstancePrivate

    EC2PriSGId:
      Description: "Security Group ID for EC2 instance"
      Value: !Ref EC2SPriSG  

        